package logic;

import java.util.ArrayList;
import java.util.List;

public class Questions {
    private static List<String> questions = new ArrayList<>(List.of(
            "Bad or Good",
    "Mildly addictive or Highly addictive",
    "Hot or Cold",
    "Normal or Weird",
    "Colorless or Colorful",
    "Low calorie or High calorie",
    "Feels bad or Feels good",
    "Inessential or Essential",
    "Cheap or Expensive",
    "Underrated weapon or Overrated weapon",
    "Rare or Common",
    "Unsexy emoji or Sexy emoji",
    "Easy subject or Hard subject",
    "Unknown or Famous",
    "Difficult to use or Easy to use",
    "Tired or Wired",
    "Dirty or Clean",
    "Requires luck or Requires skill",
    "Flavorless or Flavorful",
    "Boring topic or Fascinating topic",
    "Bad actor or Good actor",
    "Basic or Hipster",
    "Dangerous job or Safe job",
    "Fantasy or Sci-Fi",
    "Casual or Formal",
    "Underpaid or Overpaid",
    "Dry or Wet",
    "Underrated skill or Overrated skill",
    "Forbidden or Encouraged",
    "Sad song or Happy song",
    "Fragile or Durable",
    "Geek or Dork",
    "Good or Evil",
    "Worst day of the year or Best day of the year",
    "Bad habit or Good habit",
    "Cat person or Dog person",
    "Guilty pleasure or Openly love",
    "Untalented or Talented",
    "Dark or Light",
    "Underrated actor or Overrated actor",
    "Hard to find or Easy to find",
    "Ugly man or Beautiful man",
    "Hard to remember or Easy to remember",
    "Lowbrow or Highbrow",
    "Unhealthy or Healthy",
    "Bad man or Good man",
    "Historically important or Historically irrelevant",
    "Hairless or Hairy",
    "Inflexible or Flexible",
    "Normal pet or Exotic pet",
    "Introvert or Extrovert",
    "Book was better or Movie was better",
    "Bad movie or Good movie",
    "Ugly or Beautiful",
    "Happens slowly or Happens suddenly",
    "Job or Career",
    "Loved or Hated",
    "The Light Side of the Force or The Dark Side of the Force",
    "Bad pizza topping or Good pizza topping",
    "Dystopia or Utopia",
    "Mature person or Immature person",
    "Underrated thing to own or Overrated thing to own",
    "Mean person or Nice person",
    "Action movie or Adventure movie",
    "Mental activity or Physical activity",
    "Uncontroversial topic or Controversial topic",
    "Need or Want",
    "Dry food or Wet food",
    "Normal thing to own or Weird thing to own",
    "Straight or Curvy",
    "Bad person or Good person",
        "80s or 90s",
    "Ethical to eat or Unethical to eat",
    "Movie or Film",
    "Optional or Mandatory",
    "Underrated letter of the alphabet or Overrated letter of the alphabet",
    "Ordinary or Extraordinary",
    "Hard to pronounce or Easy to pronounce",
    "Low quality or High quality",
    "Unsexy animal or Sexy animal",
    "Plain or Fancy",
    "Has a bad reputation or Has a good reputation",
    "Poorly made or Well made",
    "Not a sandwich or A sandwich",
    "Quiet place or Loud place",
    "Comedy or Drama",
    "Dangerous or Safe",
    "Culturally significant or Culturally insignificant",
    "Replaceable or Irreplaceable",
    "Worst athlete of all time or Greatest athlete of all time",
    "Role model or Bad influence",
    "Useless major or Useful major",
    "Peaceful or Warlike",
    "Underrated movie or Overrated movie",
    "Rough or Smooth",
        "Bad for you or Good for you",
    "Round or Pointy",
    "Proof that God exists or Proof that God doesn’t exist",
    "Sad movie or Happy movie",
    "Waste of time or Good use of time",
    "Scary animal or Nice animal",
    "Mainstream or Niche",
    "Short lived or Long lived",
    "Nobody does it or Everybody does it",
    "Smells bad or Smells good",
    "Star Wars or Star Trek",
    "Snack or Meal",
    "Least evil company or Most evil company",
    "Soft or Hard",
    "Sustenance or Haute cuisine",
    "Square or Round",
    "Better hot or Better cold",
    "Stupid or Brilliant",
    "Artisanal or Mass produced",
    "Bad superpower or Good superpower",
    "Ineffective or Effective",
    "Unbelievable or Believable",
    "Trashy or Classy",
    "Temporary or Permanent",
    "Looks like a person or Does not look like a person",
    "Tastes bad or Tastes good",
    "Sport or Game",
    "Uncool or Cool",
    "Worst living person or Greatest living person",
    "Underrated or Overrated",
    "Messy food or Clean food",
    "Unethical or Ethical",
    "Bad gift or Good gift",
    "Unfashionable or Fashionable",
    "Freedom fighter or Terrorist",
    "Unforgiveable or Forgiveable",
    "Failure or Masterpiece",
    "Harmless or Harmful",
    "Gryffindor or Slytherin",
    "Unhygienic or Hygienic",
    "Bad music or Good music",
    "Useless or Useful",
    "Movie that Godzilla would ruin or Movie that Godzilla would improve",
    "Unimportant or Important",
    "Easy to spell or Hard to spell",
    "Vice or Virtue",
    "Underrated musician or Overrated musician",
    "Unpopular activity or Popular activity",
    "Divided or Whole",
    "Unreliable or Reliable",
    "Easy to kill or Hard to kill",
    "Unstable or Stable",
    "Round animal or Pointy animal",
    "Bad TV show or Good TV show",
    "Traditionally masculine or Traditionally feminine",
    "Useless body part or Useful body part",
    "Fad or Classic",
    "Weak or Strong",
    "Disgusting cereal or Delicious cereal",
    "Useless invention or Useful invention",
    "Liberal or Conservative",
    "Unpopular or Popular",
    "Friend or Enemy",
    "Boring or Exciting",
    "Smelly in a bad way or Smelly in a good way",
    "Villain or Hero",
    "Underrated thing to do or Overrated thing to do",
    "Useless in an emergency or Useful in an emergency",
    "For kids or For adults",
    "Wise or Intelligent",
    "Easy to do or Hard to do",
    "Worthless or Priceless",
    "Nature or Nurture",
    "Dictatorship or Democracy",
    "Normal greeting or Weird greeting",
    "Dog name or Cat name",
        "Non-partisan or Partisan",
    "Limited or Infinite",
    "Casual event or Formal event",
    "Bad investment or Good investment",
    "Small talk or Heavy topic",
    "Mild or Spicy",
    "Religious or Sacrilegious",
    "Not art or Art",
    "Illegal or Prohibited",
    "Popular or Elitist",
    "Out of control or In control",
    "Quiet or Loud",
    "Unsexy Pokémon or Sexy Pokémon",
    "Secret or Public knowledge",
    "Too small or Too big",
    "Short or Long",
    "Worst year in history or Best year in history",
    "Socialist or Capitalist",
    "Little known fact or Well known fact",
    "Stationary or Mobile",
    "Local issue or Global issue",
    "Talent or Skill",
    "Worst era to time travel or Best era to time travel",
    "The worst or The best",
    "Small number or Large number",
        "1 or 0",
    "Old fashioned or Avant garde",
    "Ugly word or Beautiful word",
    "Small or Tiny",
    "Unnatural or Natural",
    "Genuine person or Phony person",
    "Derivative or Original",
    "Etiquette or Manners",
    "Unsexy color or Sexy color",
    "Benefits you or Benefits everyone",
    "Powerless or Powerful",
        "Doesn’t vape or Vapes",
    "Fruit or Vegetable",
    "Science or Pseudoscience",
    "Funny topic or Serious topic",
    "Limp or Firm",
    "Guilty pleasure or Actually just bad",
    "Gossip or News",
    "Hard to sit on or Easy to sit on",
    "Not enough or Too much",
    "Horizontal or Vertical",
    "Unscented or Scented",
    "Huggable or Not huggable",
    "Heterogeneous or Homogenous",
    "Inclusive or Exclusive",
    "Bad dog breed or Good dog breed",
    "Art or Commerce",
    "One hit wonder or Pop icon",
    "Bad advice or Good advice",
    "Tick or Tock",
    "Bad candy or Good candy",
    "Traditional or Radical",
    "Bad mouthfeel or Good mouthfeel",
    "Illegal or Legal",
    "Deep thought or Shallow thought",
    "Bad school or Good school",
    "Never on time or Always on time",
    "Will not live to 100 or Will live to 100",
    "Bad Disney character or Good Disney character",
    "Similar or Identical",
    "Bad president or Good president",
    "Weird or Strange",
    "Famous or Infamous",
    "Least powerful god or Most powerful god",
    "Boring person or Fun person",
    "Underrated book or Overrated book",
    "Conventional wisdom or Fringe belief",
    "Worst chore or Best chore",
    "Endangered species or Overpopulated species",
    "Blue or Green",
    "Thrilling or Terrifying",
    "Nerd or Jock",
    "Expected or Unexpected",
    "Person you could beat up or  Person who’d beat you up",
    "Unreasonable phobia or Reasonable phobia",
    "Underrated game or Overrated game"
            ));

    public static List<String> getQuestions() {
        return questions;
    }
}
